### ISSUE TITLE
创建了一个播放本地音乐的版本

### ISSUE THREAD

**Issue by callmejea** [mengkunsoft/MKOnlineMusicPlayer#80]
https://github.com/callmejea/MusicPlayer
这个，不知道是否允许，没有看到license- -#
我fork之后不让提交pr，就自己创建了一个。
带服务端的，仅支持播放本地已下载的音乐，
如果不允许我就删除项目

**Comment by vlinux** [comment]
很实用！！！已星

**Comment by pplaary** [comment]
感谢 很赞 喜欢这种界面的 正好需要

**Comment by bailuWX** [comment]
大佬，我运行了，无限 现实播放失败咋办，而且每一首音乐都被改名了。。。

**Comment by pplaary** [comment]
> 

按readme来，运行没问题的

**Comment by vlinux** [comment]
github这么智能吗？有人评论直接推邮箱？ 哎其实本地版本运行也不太好。只能去网络上下载资源然后再改名字啥的。感觉最开始作者在维护的时候用着是真美好。现在背景图啥的都是死的





按readme来，运行没问题的

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pplaary** [comment]
> github这么智能吗？有人评论直接推邮箱？ 哎其实本地版本运行也不太好。只能去网络上下载资源然后再改名字啥的。感觉最开始作者在维护的时候用着是真美好。现在背景图啥的都是死的 按readme来，运行没问题的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

是的，已经用koel了，还是方便点

**Comment by vlinux** [comment]
koel是什么？是一个新的音乐盒项目吗？





github这么智能吗？有人评论直接推邮箱？ 哎其实本地版本运行也不太好。只能去网络上下载资源然后再改名字啥的。感觉最开始作者在维护的时候用着是真美好。现在背景图啥的都是死的 按readme来，运行没问题的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

是的，已经用koel了，还是方便点

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pplaary** [comment]
> koel是什么？是一个新的音乐盒项目吗？ github这么智能吗？有人评论直接推邮箱？ 哎其实本地版本运行也不太好。只能去网络上下载资源然后再改名字啥的。感觉最开始作者在维护的时候用着是真美好。现在背景图啥的都是死的 按readme来，运行没问题的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 是的，已经用koel了，还是方便点 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

也是一个本地音乐播放器，会自动扫描你本地的音乐目录并建立相关专辑、艺术家、封面的数据库

**Comment by vlinux** [comment]
牛阿 有演示站吗兄弟。我观摩观摩。





koel是什么？是一个新的音乐盒项目吗？ github这么智能吗？有人评论直接推邮箱？ 哎其实本地版本运行也不太好。只能去网络上下载资源然后再改名字啥的。感觉最开始作者在维护的时候用着是真美好。现在背景图啥的都是死的 按readme来，运行没问题的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 是的，已经用koel了，还是方便点 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

也是一个本地音乐播放器，会自动扫描你本地的音乐目录并建立相关专辑、艺术家、封面的数据库

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pplaary** [comment]
> 牛阿 有演示站吗兄弟。我观摩观摩。 koel是什么？是一个新的音乐盒项目吗？ github这么智能吗？有人评论直接推邮箱？ 哎其实本地版本运行也不太好。只能去网络上下载资源然后再改名字啥的。感觉最开始作者在维护的时候用着是真美好。现在背景图啥的都是死的 按readme来，运行没问题的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 是的，已经用koel了，还是方便点 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 也是一个本地音乐播放器，会自动扫描你本地的音乐目录并建立相关专辑、艺术家、封面的数据库 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

你加我q 2095553008

**Comment by vlinux** [comment]
添加了





牛阿 有演示站吗兄弟。我观摩观摩。 koel是什么？是一个新的音乐盒项目吗？ github这么智能吗？有人评论直接推邮箱？ 哎其实本地版本运行也不太好。只能去网络上下载资源然后再改名字啥的。感觉最开始作者在维护的时候用着是真美好。现在背景图啥的都是死的 按readme来，运行没问题的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 是的，已经用koel了，还是方便点 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 也是一个本地音乐播放器，会自动扫描你本地的音乐目录并建立相关专辑、艺术家、封面的数据库 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

你加我q 2095553008

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by callmejea** [comment]
或者说：面向的不是本地听歌～本地听歌是有很多的解决方案的比如系统自带的music挺好
这个面向的是有自己服务器且经常听歌的。
比如我：iPhone，Mac，CarPlay，家里，公司，我只需要维护一份音乐源就好了～
